apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.podName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: http
  selector:
    k8s-app: {{ .Values.global.podName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.redisName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: redis
  selector:
    k8s-app: {{ .Values.global.redisName }}
